import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({subsets:['latin']})

export const metadata: Metadata = {
  title: "CashTracker - Inicio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={outfit.className}>
        <>
          <h1>Header</h1>
          {children}
          <h1>Footer</h1>
        </>
      </body>
    </html>
  );
}
